name: Deploy to Azure App Service

on:
  push:
    tags:
      - 'v*'

env:
  AZURE_REGION: East US
  WEBAPP_NAME: quivr-webapp
  IMAGE_NAME: backend:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name: production  # Optionally, specify a deployment slot
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        package: ./backend  # Specify the path to your application code
